#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 

bspc config border_width         	2
bspc config window_gap          	12
bspc config -m HDMI-A-1 top_padding	36

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius        6

~/.config/themes/current/config.sh

bspc config remove_unplugged_monitors true
bspc config remove_disable_monitors true

feh --bg-fill $HOME/.config/themes/current/background.png

xrdb ~/.config/themes/current/.Xressources

~/.config/polybar/launch.sh

alacritty --hold -e bash -c 'echo "Update your System MORON" && yay -Syu && echo "Ich habe fertig."'
